version: "3"
services:
  app: &app
    image: ghcr.io/vas3k/infomate:${GITHUB_SHA:-latest}
    command: make docker-run-app
    container_name: infomate_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://infomate.club
      - POSTGRES_DB=infomate
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=vas3k
      - POSTGRES_HOST=postgres
    env_file:
      - .env
    restart: always
    ports:
      - "127.0.0.1:8816:8816"

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: infomate_cron
    depends_on:
      - app
    ports: []

  postgres:
    image: postgres:15
    container_name: infomate_postgres
    restart: always
    environment:
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: vas3k
      POSTGRES_DB: infomate
    volumes:
      - /home/vas3k/pgdata/infomate:/var/lib/postgresql/data:rw

  migrate_and_init:
    <<: *app
    container_name: infomate_init_feeds
    restart: "no"
    ports: []
    depends_on:
      - app
    command: make feed_init feed_refresh

