version: '3.7'

services:
  infomate_app: &app
    build:
      context: .
      args:
        requirements: requirements.txt
    command: make docker-run-app
    container_name: infomate_app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=infomate
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=vas3k
      - POSTGRES_HOST=postgres
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: infomate_postgres
    environment:
        - POSTGRES_USER=vas3k
        - POSTGRES_PASSWORD=vas3k
        - POSTGRES_DB=infomate
    ports:
        - "54321:5432"

  migrate_and_init:
    <<: *app
    container_name: infomate_migrate_and_init
    restart: "no"
    ports: []
    command: make migrate feed_init feed_refresh

