version: '3.7'

services:
  infomate_app: &app
    image: cr.yandex/crpucd93gvncjg9sp45g/infomateclub_infomate_app
#    build:
#      context: .
#      args:
#        requirements: requirements.txt
    command: make docker_run
    container_name: infomate_app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:11
    container_name: infomate_postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=infomate
    ports:
        - "54321:5432"

  migrate_and_init:
    <<: *app
    container_name: infomate_migrate_and_init
    restart: "no"
    ports: []
    command: make migrate feed_init # feed_refresh # <-- uncomment to parse some data
